import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, mkdtemp, writeFile, readFile, rm } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { createRequire } from "node:module";
import { chromium } from "playwright-core";
import JSZip from "jszip";
const require = createRequire(import.meta.url);
const { webpack } = require("next/dist/compiled/webpack/webpack.js");
const repo = path.resolve(import.meta.dirname, "..");

test("maximized transfer workspace resizes, remembers size and deletes files without discarding failed drafts", { timeout: 120000 }, async () => {
  const root = await mkdtemp(path.join(tmpdir(), "piora-transfer-ui-"));
  let browser;
  try {
    await writeFile(path.join(root, "loader.cjs"), `const ts=require(${JSON.stringify(require.resolve("typescript"))});module.exports=s=>ts.transpileModule(s,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText`);
    await writeFile(path.join(root, "css.cjs"), `module.exports=s=>"export default "+JSON.stringify(Object.fromEntries([...s.matchAll(/\\.([a-zA-Z][\\w-]*)/g)].map(m=>[m[1],m[1]])))`);
    await writeFile(path.join(root, "body.tsx"), `export const MarkdownBody=({children})=><div>{children}</div>;`);
    await writeFile(path.join(root, "storage.tsx"), `export const CompanionStorageSettings=()=>null;`);
    await writeFile(path.join(root, "entry.tsx"), `import React from "react";import {createRoot} from "react-dom/client";import {CompanionTransferStation} from ${JSON.stringify(path.join(repo, "components/CompanionTransferStation.tsx"))};
const initial=[{id:"a",kind:"note",title:"文档 A",content:"原始内容",updatedAt:1},{id:"b",kind:"note",title:"文档 B",content:"另一份内容",updatedAt:1},{id:"image",kind:"image",title:"图片",content:"data:image/png;base64,iVBORw0KGgo=",updatedAt:1}];
window.records=initial;window.writes=[];function App(){const [items,setItems]=React.useState(initial);return <main className="content" data-tool="library" style={{padding:24}}><div className="libraryPane"><CompanionTransferStation items={items} loaded loading={false} pending={false} error="" refresh={async()=>{}} write={async(method,input)=>{window.writes.push(input);if(window.failSave&&input.content!==undefined)throw new Error("保存失败测试");if(window.failDelete&&(input.remove||input.trash))throw new Error("删除失败测试");if(method==='POST'){if(window.failCreateCountdown){window.failCreateCountdown--;if(window.failCreateCountdown===0)throw new Error("导入写入失败测试")}const next={id:'created-'+window.writes.length,pinned:false,createdAt:Date.now(),updatedAt:Date.now(),kind:input.kind||'note',...input};window.records=[next,...window.records];setItems([...window.records]);return [next,...window.records.slice(1)]}if(input.remove)window.records=window.records.filter(x=>x.id!==input.id);else window.records=window.records.map(x=>{if(x.id!==input.id)return x;const next={...x,...input,updatedAt:x.updatedAt+1};if(input.trash)next.deletedAt=Date.now();if(input.restore)delete next.deletedAt;return next});setItems([...window.records]);return window.records;}}/></div></main>};createRoot(document.getElementById("root")).render(<App/>);`);
    const compiler = webpack({ mode: "development", target: "web", devtool: false, entry: path.join(root, "entry.tsx"), output: { path: root, filename: "bundle.js", publicPath: "http://transfer-ui.test/" }, resolve: { extensions: [".tsx", ".ts", ".js"], modules: [path.join(repo, "node_modules"), "node_modules"], alias: { "@": repo } }, plugins: [new webpack.NormalModuleReplacementPlugin(/^\.\/MarkdownBody$/, path.join(root, "body.tsx")), new webpack.NormalModuleReplacementPlugin(/^\.\/CompanionStorageSettings$/, path.join(root, "storage.tsx"))], module: { rules: [{ test: /\.tsx?$/, exclude: /node_modules/, use: path.join(root, "loader.cjs") }, { test: /\.css$/, use: path.join(root, "css.cjs") }] } });
    await new Promise((resolve, reject) => compiler.run((error, stats) => compiler.close(() => error || stats.hasErrors() ? reject(error || new Error(stats.toString({ all: false, errors: true }))) : resolve())));
    browser = await chromium.launch({ channel: "msedge", headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = []; page.on("pageerror", (error) => errors.push(error.message));
    const css = (await readFile(path.join(repo, "components/CompanionTransferStation.module.css"), "utf8")).replace(/:global\(([^)]+)\)/g, "$1");
    const editorCss = await readFile(path.join(repo, "components/MarkdownEditor.css"), "utf8");
    // Only include the parent's layout constraints: other CSS module class names
    // are scoped in production and must not collide with this fixture's map.
    const panelCss = '.content{height:100dvh;overflow:auto;min-height:0}' + (await readFile(path.join(repo, "components/CompanionPanel.module.css"), "utf8")).split("\n").filter((line) => line.startsWith(".content >") || line.startsWith('.content[data-tool="library"]') || line.startsWith('.libraryPane')).join("\n");
    await page.route("http://transfer-ui.test/**", async (route) => {
      const url = new URL(route.request().url());
      if (url.pathname.endsWith(".js")) await route.fulfill({ contentType: "text/javascript", body: await readFile(path.join(root, path.basename(url.pathname))) });
      else await route.fulfill({ contentType: "text/html", body: `<!doctype html><meta charset="utf-8"><style>:root{--text:#ddd;--text-muted:#aaa;--text-dim:#888;--bg:#171b22;--bg-panel:#202630;--bg-hover:#303945;--bg-selected:#334151;--border:#39434f;--accent:#a8c3aa;--ui-font-size:14px;--text-xs:12px;--text-sm:13px;--text-base:14px;--text-lg:18px;--text-xl:20px}*{box-sizing:border-box}body{margin:0;background:var(--bg);font:14px system-ui}${panelCss}${css}${editorCss}</style><div id="root"></div><script src="/bundle.js"></script>` });
    });
    await page.goto("http://transfer-ui.test/");
    const frame = page.locator(".workspaceFrame");
    await frame.waitFor();
    const richText = page.locator('.cm-content[contenteditable="true"]').first();
    await richText.waitFor();
    const initialBounds = await frame.boundingBox(); assert.ok(initialBounds.width > 1000, "maximization removes the old 880px cap");
    assert.ok(Math.abs(initialBounds.y + initialBounds.height - 976) < 2, "the editor fills the remaining window height");
    assert.ok((await richText.boundingBox()).width > 1000, "the editable body grows with the workspace instead of staying at 820px");
    const editorViewport = page.locator('.cm-scroller').first();
    assert.ok((await editorViewport.boundingBox()).height > initialBounds.height * .7, "most workspace height belongs to editable content");
    assert.ok(await page.locator('.content').evaluate(el => el.scrollHeight <= el.clientHeight + 2), "editing uses its own scroll area without pushing the workspace below the window");
    // Selecting text stays quiet; the stable, viewport-bound context menu opens only on right click.
    await richText.fill('选区菜单');
    await richText.press('Control+A');
    assert.equal(await page.getByRole('menu', { name: 'Markdown 编辑菜单' }).count(), 0);
    await richText.click({ button: 'right' });
    const contextMenu = page.getByRole('menu', { name: 'Markdown 编辑菜单' });
    await contextMenu.waitFor();
    const menuBounds = await contextMenu.boundingBox();
    assert.ok(menuBounds.x >= 8 && menuBounds.y >= 8 && menuBounds.x + menuBounds.width <= 1432 && menuBounds.y + menuBounds.height <= 992);
    await contextMenu.getByRole('menuitem', { name: /加粗/ }).click();
    await page.getByRole('button', { name: '源码', exact: true }).click();
    assert.equal(await page.getByLabel('Markdown 源码', { exact: true }).textContent(), '**选区菜单**');
    assert.ok(await page.locator('.cm-gutters').isVisible(), 'source mode shows line numbers');
    await page.getByRole('button', { name: '即时排版', exact: true }).click();
    assert.equal(await page.locator('.cm-gutters').isVisible(), false, 'live mode keeps the writing surface clean');
    await richText.press('Control+A');
    await page.getByTitle('插入或编辑链接').click();
    const linkDialog = page.getByRole('dialog', { name: '编辑链接' });
    await linkDialog.getByLabel('链接地址').fill('https://example.com/a b');
    await linkDialog.getByRole('button', { name: '应用', exact: true }).click();
    await page.getByRole('button', { name: '源码', exact: true }).click();
    assert.equal(await page.getByLabel('Markdown 源码', { exact: true }).textContent(), '[**选区菜单**](https://example.com/a%20b)');
    await page.getByRole('button', { name: '即时排版', exact: true }).click();
    await richText.press('Control+A');
    await richText.evaluate((element) => { const data = new DataTransfer(); data.setData('text/html', '<h2>富文本</h2><ul><li>第一项</li><li>第二项</li></ul><a href="https://example.com">官网</a><script>bad()</script>'); data.setData('text/plain', '降级文本'); element.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: data })); });
    await page.getByRole('button', { name: '源码', exact: true }).click();
    const pasted = await page.getByLabel('Markdown 源码', { exact: true }).evaluate(element => element.innerText);
    assert.match(pasted, /^富文本\n(?:={3,}|-{3,})|^## 富文本/); assert.match(pasted, /-\s+第一项/); assert.match(pasted, /\[官网\]\(https:\/\/example\.com\)/); assert.doesNotMatch(pasted, /bad\(\)/);
    await page.getByRole('button', { name: '即时排版', exact: true }).click();
    await page.getByRole('button', { name: '查找与替换', exact: true }).click();
    await page.locator('.cm-search').waitFor();
    assert.equal(await page.getByRole('button', { name: '即时排版', exact: true }).getAttribute('aria-pressed'), 'true', 'find does not force source mode');
    await richText.press('Escape');
    await richText.press('Control+H'); await page.locator('.cm-search').waitFor(); await richText.press('Escape');

    // Markdown-looking text inside a code fence stays code and never turns into live objects.
    await page.getByRole('button', { name: '源码', exact: true }).click();
    await page.getByLabel('Markdown 源码', { exact: true }).fill('```markdown\n# 代码标题\n- [ ] 代码任务\n| A | B |\n| --- | --- |\n![代码图片](data:image/png;base64,iVBORw0KGgo=)\n```\n\n尾部');
    await page.getByLabel('Markdown 源码', { exact: true }).press('Control+End');
    await page.getByRole('button', { name: '即时排版', exact: true }).click();
    assert.equal(await page.locator('.cm-md-table').count(), 0); assert.equal(await page.locator('.cm-md-image').count(), 0); assert.equal(await page.locator('.cm-md-task').count(), 0);

    // Tables and images use object editors without detached, free-floating Vditor panels.
    await page.getByRole('button', { name: '源码', exact: true }).click();
    await page.getByLabel('Markdown 源码', { exact: true }).fill('| A | B |\n| --- | --- |\n| 1 | 2 |\n\n尾部');
    await page.getByLabel('Markdown 源码', { exact: true }).press('Control+End');
    await page.getByRole('button', { name: '即时排版', exact: true }).click();
    await page.waitForTimeout(300);
    assert.deepEqual(errors, [], await richText.textContent());
    const tableCell = page.locator('.cm-md-table td').filter({ hasText: '2' });
    await tableCell.waitFor();
    await tableCell.click({ button: 'right' });
    await page.getByRole('menuitem', { name: '在下方插入行', exact: true }).click();
    await page.locator('.cm-md-table td').filter({ hasText: '2' }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: '右对齐当前列', exact: true }).click();
    assert.equal(await page.locator('.cm-md-table td').filter({ hasText: '2' }).evaluate(element => element.style.textAlign), 'right');
    await page.locator('.cm-md-table td').filter({ hasText: '2' }).fill('新值');
    await page.locator('.cm-md-table td').filter({ hasText: '新值' }).press('Tab');
    // Tab commits rebuild the table and restore focus on the next animation
    // frame. Let that finish before focusing another cell, or the pending
    // callback can move focus back while the next key press is in flight.
    await page.waitForFunction(() => document.activeElement?.matches('.cm-md-table td[data-row="3"][data-column="0"]'));
    assert.equal(await page.locator('.cm-md-table td').count(), 4, 'Tab into the existing row does not append another row');
    const lastCell = page.locator('.cm-md-table td').last();
    await lastCell.focus(); await lastCell.press('Tab');
    await page.waitForFunction(() => document.activeElement?.matches('.cm-md-table td[data-row="4"][data-column="0"]'));
    assert.equal(await page.locator('.cm-md-table td').count(), 6, 'Tab from the final cell appends exactly one row and focuses its first cell');
    await page.getByRole('button', { name: '源码', exact: true }).click();
    assert.match(await page.getByLabel('Markdown 源码', { exact: true }).textContent(), /\| 1 \| 新值 \|/);
    await page.getByLabel('Markdown 源码', { exact: true }).fill('![示例](data:image/png;base64,iVBORw0KGgo=)\n\n尾部');
    await page.getByLabel('Markdown 源码', { exact: true }).press('Control+End');
    await page.getByRole('button', { name: '即时排版', exact: true }).click();
    await page.locator('.cm-md-image').click();
    await page.getByRole('dialog', { name: '编辑图片' }).waitFor();
    await page.getByLabel('宽度（像素）').fill('320');
    await page.getByRole('dialog', { name: '编辑图片' }).getByRole('button', { name: '应用', exact: true }).click();
    await page.getByRole('button', { name: '源码', exact: true }).click();
    assert.match(await page.getByLabel('Markdown 源码', { exact: true }).textContent(), /<img[^>]+width="320">/);
    await page.getByLabel('Markdown 源码', { exact: true }).press('Control+End');
    await page.getByRole('button', { name: '即时排版', exact: true }).click();
    assert.equal(await page.locator('.cm-md-image img').evaluate(element => element.style.width), '320px');
    const archive = new JSZip();
    archive.file('docs/导入稿.md', '![附件](../images/pixel.png)\n\nZIP 正文');
    archive.file('images/pixel.png', Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6EAAAAABJRU5ErkJggg==', 'base64'));
    const archiveBuffer = await archive.generateAsync({ type: 'nodebuffer' });
    const zipInput = { name: 'portable.zip', mimeType: 'application/zip', buffer: archiveBuffer };
    await page.locator('section.station > input[type="file"]').setInputFiles(zipInput);
    const importDialog = page.getByRole('dialog', { name: '确认导入' });
    await importDialog.waitFor();
    assert.match(await importDialog.textContent(), /Markdown 文档\s*1/);
    assert.match(await importDialog.textContent(), /图片与附件\s*1/);
    assert.equal(await page.evaluate(() => window.records.some(item => item.title === '导入稿')), false, 'preview does not mutate storage');
    await importDialog.getByRole('button', { name: '取消', exact: true }).click();
    assert.equal(await importDialog.count(), 0);
    assert.equal(await page.evaluate(() => window.records.some(item => item.title === '导入稿')), false, 'cancel leaves storage untouched');
    await page.locator('section.station > input[type="file"]').setInputFiles(zipInput);
    await importDialog.getByRole('button', { name: '确认导入', exact: true }).click();
    await page.waitForFunction(() => window.records.some(item => item.title === '导入稿' && item.content.includes('/api/companion/library/image') === false && item.content.includes('data:image/png')));
    const rollbackArchive = new JSZip();
    rollbackArchive.file('回滚一.md', '第一份'); rollbackArchive.file('回滚二.md', '第二份');
    await page.evaluate(() => { window.failCreateCountdown = 2; });
    await page.locator('section.station > input[type="file"]').setInputFiles({ name: 'rollback.zip', mimeType: 'application/zip', buffer: await rollbackArchive.generateAsync({ type: 'nodebuffer' }) });
    await importDialog.getByRole('button', { name: '确认导入', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: '导入写入失败测试 已撤销本次已创建的内容。' }).waitFor();
    assert.equal(await page.evaluate(() => window.records.some(item => item.title === '回滚一' || item.title === '回滚二')), false, 'failed batch import rolls back prior writes');
    await page.evaluate(() => { window.failCreateCountdown = 0; });
    await mkdir(path.join(repo, ".verification"), { recursive: true });
    await page.screenshot({ path: path.join(repo, ".verification/transfer-workspace-expanded.png") });
    const initialFont = await page.locator(".heading h1").evaluate(element => getComputedStyle(element).fontSize);
    await page.setViewportSize({ width: 900, height: 720 });
    await page.waitForFunction(() => Math.abs(document.querySelector('.workspaceFrame').getBoundingClientRect().bottom - 696) < 2);
    assert.ok((await frame.boundingBox()).width < initialBounds.width);
    assert.equal(await page.locator(".heading h1").evaluate(element => getComputedStyle(element).fontSize), initialFont);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.waitForFunction(() => Math.abs(document.querySelector('.workspaceFrame').getBoundingClientRect().bottom - 976) < 2);
    assert.deepEqual(errors, []);
    const right = page.getByRole("separator", { name: "从右侧调整中转站宽度" });
    const bounds = await right.boundingBox();
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + 50); await page.mouse.down(); await page.mouse.move(bounds.x - 180, bounds.y + 50, { steps: 10 }); await page.mouse.up();
    const narrower = await frame.boundingBox(); assert.ok(narrower.width < initialBounds.width - 250);
    const bottom = page.getByRole("separator", { name: "调整中转站高度" });
    await bottom.focus(); await bottom.press("Shift+ArrowUp"); await bottom.press("Shift+ArrowUp");
    const shorter = await frame.boundingBox();
    await bottom.press("ArrowDown");
    const bottomBounds = await bottom.boundingBox();
    await page.mouse.move(bottomBounds.x + bottomBounds.width / 2, bottomBounds.y + 6); await page.mouse.down();
    await page.mouse.move(bottomBounds.x + bottomBounds.width / 2, bottomBounds.y + 46, { steps: 8 }); await page.mouse.up();
    const beforeCorner = await frame.boundingBox();
    const corner = await page.getByRole("button", { name: "调整中转站宽度和高度", exact: true }).boundingBox();
    await page.mouse.move(corner.x + 10, corner.y + 10); await page.mouse.down();
    await page.mouse.move(corner.x + 30, corner.y + 30, { steps: 8 }); await page.mouse.up();
    const taller = await frame.boundingBox(); assert.ok(taller.height > shorter.height);
    assert.ok(taller.width > beforeCorner.width && taller.height > beforeCorner.height);
    await page.reload(); await frame.waitFor();
    await page.waitForFunction((width) => Math.abs(document.querySelector(".workspaceFrame").getBoundingClientRect().width - width) < 2, taller.width);
    assert.ok(Math.abs((await frame.boundingBox()).height - taller.height) < 2);
    await page.getByRole("button", { name: "字号与版式", exact: true }).click();
    const fontSize = page.getByRole("spinbutton", { name: "自定义字号" });
    await richText.waitFor();
    await fontSize.fill("28");
    await page.waitForFunction(() => getComputedStyle(document.querySelector('.cm-content[contenteditable="true"]')).fontSize === "28px");
    await page.getByRole('button', { name: '源码', exact: true }).click();
    assert.equal(await page.getByLabel('Markdown 源码', { exact: true }).evaluate(el => getComputedStyle(el).fontSize), "28px", "source editing uses the selected size too");
    await page.getByRole('button', { name: '即时排版', exact: true }).click();
    await page.getByRole("button", { name: "阅读", exact: true }).click();
    assert.equal(await page.locator('.readingPreview').evaluate(el => getComputedStyle(el).fontSize), "28px");
    await page.getByRole("button", { name: "编辑", exact: true }).click();
    await page.screenshot({ path: path.join(repo, ".verification/transfer-font-size.png") });
    await page.reload(); await richText.waitFor();
    await page.waitForFunction(() => getComputedStyle(document.querySelector('.cm-content[contenteditable="true"]')).fontSize === "28px");
    await page.getByRole("button", { name: "字号与版式", exact: true }).click();
    assert.equal(await fontSize.inputValue(), "28");
    await fontSize.fill("100"); await fontSize.press("Tab");
    assert.equal(await fontSize.inputValue(), "48");
    await fontSize.fill(""); await fontSize.press("Tab");
    assert.equal(await fontSize.inputValue(), "48");
    await page.getByRole("button", { name: "恢复默认", exact: true }).click();
    assert.ok((await frame.boundingBox()).width > 1000);
    await page.getByRole('button', { name: '固定栏宽', exact: true }).click();
    assert.ok((await richText.boundingBox()).width <= 822, 'fixed-width mode retains a readable column');
    await page.reload(); await richText.waitFor();
    await page.waitForFunction(() => document.querySelector('[data-writing-layout]').dataset.writingLayout === 'fixed');
    assert.ok((await richText.boundingBox()).width <= 822, 'fixed-width choice survives reload');
    await page.getByRole('button', { name: '字号与版式', exact: true }).click();
    await page.getByRole('button', { name: '自适应宽度', exact: true }).click();
    assert.ok((await richText.boundingBox()).width > 1000);
    await page.getByRole('button', { name: '字号与版式', exact: true }).click();
    await right.focus(); await right.press('Shift+ArrowLeft');
    const manualWidth = (await frame.boundingBox()).width;
    await page.getByRole('button', { name: '大纲', exact: true }).click();
    await page.getByRole('button', { name: '专注', exact: true }).click();
    assert.ok((await frame.boundingBox()).width > manualWidth + 50, 'focus mode fills the available workspace');
    assert.equal(await page.locator('.fileSidebar').isVisible(), false);
    assert.equal(await page.getByRole('navigation', { name: '文档大纲' }).isVisible(), false);
    await page.screenshot({ path: path.join(repo, '.verification/transfer-workspace-focus.png') });
    await page.getByRole('button', { name: '退出专注', exact: true }).click();
    assert.ok(Math.abs((await frame.boundingBox()).width - manualWidth) < 2, 'leaving focus restores the manually sized workspace');
    await page.getByRole('button', { name: '大纲', exact: true }).click();
    await page.getByRole('button', { name: '铺满中转站工作区', exact: true }).click();
    assert.ok(Math.abs((await frame.boundingBox()).width - initialBounds.width) < 2);
    await page.setViewportSize({ width: 600, height: 800 });
    assert.ok((await richText.boundingBox()).width <= 600, 'fluid text fits a narrow window');
    assert.ok((await editorViewport.boundingBox()).height > 350, 'narrow layouts still leave room to write');
    await page.screenshot({ path: path.join(repo, '.verification/transfer-workspace-narrow.png') });
    await page.setViewportSize({ width: 1440, height: 1000 });
    // Delete an unopened file without disturbing the active document.
    await page.getByRole("button", { name: "删除 文档 B", exact: true }).click();
    await page.getByRole("button", { name: "取消", exact: true }).click();
    assert.equal(await page.getByRole("button", { name: "删除 文档 B", exact: true }).count(), 1);
    await page.getByRole("button", { name: "删除 文档 B", exact: true }).click();
    await page.getByRole("button", { name: "确认删除", exact: true }).click();
    await page.waitForFunction(() => window.records.find(x => x.id === "b")?.deletedAt);
    assert.equal(await page.getByRole("tab", { name: "文档 A", exact: true }).count(), 1);
    // Refuse deletion if an open editor cannot save its draft.
    await page.getByRole('button', { name: '源码', exact: true }).click();
    await page.getByLabel("Markdown 源码", { exact: true }).fill("不能丢的草稿");
    await page.evaluate(() => { window.failSave = true; });
    await page.getByRole("button", { name: "删除 文档 A", exact: true }).click();
    await page.getByRole("button", { name: "确认删除", exact: true }).click();
    await page.getByText("文档尚未保存，未删除文件。请先保存或另存副本。", { exact: true }).waitFor();
    assert.equal(await page.getByLabel("Markdown 源码", { exact: true }).textContent(), "不能丢的草稿");
    assert.ok(await page.evaluate(() => window.records.some(x => x.id === "a" && !x.deletedAt)));
    await page.evaluate(() => { window.failSave = false; window.failDelete = true; });
    await page.getByRole("button", { name: "确认删除", exact: true }).click();
    await page.getByText("删除失败测试", { exact: true }).waitFor();
    assert.equal(await page.getByRole("tab", { name: "文档 A", exact: true }).count(), 1);
    await page.evaluate(() => { window.failDelete = false; });
    await page.getByRole("button", { name: "确认删除", exact: true }).click();
    await page.waitForFunction(() => window.records.find(x => x.id === "a")?.deletedAt);
    assert.equal(await page.getByRole("tab", { name: "文档 A", exact: true }).count(), 0);
    assert.ok(await page.evaluate(() => window.writes.some(x => x.id === "a" && x.content?.trim() === "不能丢的草稿")), "draft saved before deletion");
    await page.getByRole('button', { name: /回收站 2/, exact: true }).click();
    const trash = page.getByRole('region', { name: '中转站回收站' });
    await trash.locator('.trashList > div').filter({ hasText: '文档 B' }).getByRole('button', { name: '恢复', exact: true }).click();
    await page.waitForFunction(() => !window.records.find(x => x.id === 'b')?.deletedAt);
    const trashedA = trash.locator('.trashList > div').filter({ hasText: '文档 A' });
    await trashedA.getByRole('button', { name: '永久删除', exact: true }).click();
    await trashedA.getByRole('button', { name: '确认永久删除', exact: true }).click();
    await page.waitForFunction(() => !window.records.some(x => x.id === 'a'));
    await mkdir(path.join(repo, ".verification"), { recursive: true });
    await page.screenshot({ path: path.join(repo, ".verification/transfer-workspace.png") });
    assert.deepEqual(errors, []);
  } finally { await browser?.close(); await rm(root, { recursive: true, force: true }); }
});
