import type { ArkUiAstFile, ArkUiAstNode } from "./types";

const INDENT = "  ";

function commentText(value: string): string {
  return value.replace(/[\r\n\u2028\u2029]+/g, " ").replace(/\*\//g, "* /").slice(0, 512);
}

function printNode(node: ArkUiAstNode, depth: number): string[] {
  const indent = INDENT.repeat(depth);
  const output: string[] = [];
  if (node.comment) output.push(`${indent}// ${commentText(node.comment)}`);
  output.push(`${indent}// Design node ${commentText(node.sourceNodeId)}`);
  const constructor = `${node.component}(${node.constructorArguments.join(", ")})`;
  if (node.children.length) {
    output.push(`${indent}${constructor} {`);
    for (const child of node.children) output.push(...printNode(child, depth + 1));
    output.push(`${indent}}`);
  } else {
    output.push(`${indent}${constructor}`);
  }
  for (const modifier of node.modifiers) {
    output.push(`${indent}${INDENT}.${modifier.name}(${modifier.arguments.join(", ")})`);
  }
  return output;
}

export function printArkUiFile(file: ArkUiAstFile, generatorVersion: string): string {
  const output = [
    "/**",
    " * Generated by Piora Design to Harmony.",
    ` * Generator: ${generatorVersion}`,
    ` * Root design node: ${commentText(file.sourceNodeId)}`,
    " * Managed file: review generated changes before applying to the project.",
    " */",
  ];
  if (file.imports.length) {
    output.push("");
    for (const item of file.imports) output.push(`import { ${item.symbols.join(", ")} } from ${JSON.stringify(item.path)}`);
  }
  output.push("", "@Component", `export struct ${file.symbolName} {`);
  for (const method of file.methods) {
    output.push(`${INDENT}private ${method.name}(): void {`);
    for (const line of method.body) output.push(`${INDENT}${INDENT}${line}`);
    output.push(`${INDENT}}`, "");
  }
  output.push(`${INDENT}build() {`, ...printNode(file.root, 2), `${INDENT}}`, "}", "");
  return output.join("\n");
}
